### ISSUE TITLE
din-skip/din-skip-mid Detection/Error

### ISSUE THREAD

**Issue by gnawh** [pixeltris/TwitchAdSolutions#1]
When enabling din-skip via UB or Tampermonkey, you get infinite reload.

When enabling din-skip-mid via UB or Tampermonkey, you get the following error:
**Your device does not support playback of this premium content. Please try a different device. (Error #2)**

**Comment by gnawh** [comment]
Seems to be working after removing `twitch.tv##+js(twitch-videoad)` from UB filter.

**Comment by pixeltris** [comment]
If din-skip gives an infinite reload, then the other one wont work any better as the server is always giving an ad result. It's possible that the request to skip the ad is being denied. There currently isn't any fallback logic in cases where skipping ads fails.

**Comment by pixeltris** [comment]
https://github.com/pixeltris/TwitchAdSolutions/commit/bc0303d46036a6946d35e6b22f3f6753483b0175 this commit removes the additional modifications of the requests. dyn-skip-min is now dyn-skip as the reload is less than ideal. Hopefully the playback issues are fixed.

**Comment by c133** [comment]
Hi pixeltris, thanks for your work.
I had an issue just now, not sure if it's related to the above or not.

I am using dyn-skip-mid, via UB. 
It results in the infinite reload.

Is there anything wrong I am doing on my end?
Is there any difference if I use greasemonkey instead?
I shouldn't have to update the URL in UB since any pushes you make on git will update the code which UB will 'see' right?

Thank you.

**Comment by pixeltris** [comment]
`dyn-skip-midroll` will reload the player if it detects an ad segment. The method it uses cannot be combined with any script which sets `embed` (e.g. it can't be combined with ttv-ublock), doing so will result in an infinite reload.

I'm not sure if ublock updates the urls, or if they are cached. There haven't been updates to `dyn-skip-midroll` since I made it though.

There might be other cases where the skip doesn't work (which would result in an infinite reload), but the only case I'm currently aware of is `embed`. You can test it operates as expected outside of a web browser by using `utils.cs` (run `utils.bat`, then run the exe it builds - assuming you're on Windows). This will simulate what the extension does, to confirm that it *should* work.

**Comment by c133** [comment]
I'm sorry, just noticed that I still had my ttv-ublock extension turned on. Thank you!

**Comment by c133** [comment]
Ok, so even after removing ttv-ublock (Removing extension from browser, deleted extension files..), and restarting my browser, I am still getting infinite reload. I double checked my extensions and don't have any other twitch extensions besides better twitch tv which I turned off just in case and I'm still eventually get infinite reload. So I guess there must be cases other than embed?

**Comment by pixeltris** [comment]
Yes that would be my assumption that there are cases other than `embed`. I'd recommend trying the `utils.cs` thing mentioned above to confirm this. If that fails to show "has ad" followed by "no ad" in further requests then using this method definitely isn't an option for you. If it does work then it should work, but either something is externally interfering with it, or there's a bug in the script.

**Comment by pixeltris** [comment]
Alternatively `proxy-m3u8` is a great solution if `dyn-skip-midroll` doesn't work. `proxy-m3u8` depends on a third party, but pretty guarantees no ads will get through (assuming the third party operates as expected).

**Comment by TheHungryGeek** [comment]
I have the same issue with dyn-skip-mid as well, infinite reload. Currently using proxy-m3u8, working perfectly.

Thank you for all your work on this, Twitch devs are not going to be able to whack all the moles given the number of work arounds you've made.

**Comment by pixeltris** [comment]
I've observed an infinite re-load today. Here is what happened for me:

1) When the player loaded, it detected an an ad-free stream.
2) When the main stream starts up an ad segment comes in (towards the end of the m3u8 / after many `live` segments).
3) The player refresh kicks in due to the detected ad, and this process repeats.

Because no ad was detected in the initial request, it never sends the "watched ad" state. A possible fix for this might be changing the script to notify Twitch that the ad was watched before doing the player refresh.

**Comment by c133** [comment]
Thank you for continuing to work on this. I just started using the m3u8 script today, will report back any findings.

**Comment by pixeltris** [comment]
After making the changes mentioned in my previous comment, I still got infinite reload on midroll ads.

In this commit https://github.com/pixeltris/TwitchAdSolutions/commit/f743a866ca73b5b75c87ff231c9f8da9a381493f I added a new variant called `dyn-skip-midroll-alt` which doesn't spam the player reload as much, and instead opts for using a lower resolution stream (mixed in with player reloads every 10 seconds). Improvements could definitely be made.

The reason why I don't think that the original technique works on midrolls is because the technique involves notifying Twitch that ads were watched, and then requesting a new stream. I think when midrolls play they will ALWAYS play on each refresh no matter what (as the streamer is manually doing this, there's a clearly defined server time when ads are playing for all users).

**Comment by c133** [comment]
Hi @pixeltris I just started noticing something with the proxy method. Past few days when I switch between streams, there is a slight 2-3 second delay which I know is normal. Right now that delay is really long....like 10+ seconds. Is this due to the proxy server being overloaded or some other reason? Thank you.

**Comment by pixeltris** [comment]
It could be something like that yea. You could tweak the code a little bit and use the other proxy server. The tweaks you'd need to make:

https://github.com/pixeltris/TwitchAdSolutions/blob/9692563c83e9e416c6a0f158d1b6e483c209c988/proxy-m3u8/proxy-m3u8-ublock-origin.js#L16

Should be changed to `scope.OPT_MODE_PROXY_M3U8 = 'https://got-greedy.corblimey.workers.dev/';`

https://github.com/pixeltris/TwitchAdSolutions/blob/9692563c83e9e416c6a0f158d1b6e483c209c988/proxy-m3u8/proxy-m3u8-ublock-origin.js#L268

Should be changed to `url = OPT_MODE_PROXY_M3U8;`

**Comment by pixeltris** [comment]
Closing this as the issues with `dyn-skip`, `dyn-skip-midroll`, and `dyn-skipmidroll-alt` are detailed in the README. Improvements still need to be made to the segment removal (fix loops/stutters), but that's a separate issue.
