### ISSUE TITLE
Scripts No longer blocking

### ISSUE THREAD

**Issue by The18thPrimarch** [pixeltris/TwitchAdSolutions#243]
Seems as of last night the scripts are no longer working to block ads. I primarily alternate between AdGuard Extra, Vaft, and VideoSwapNew and none of those 3 are working anymore.

**Comment by dombobble** [comment]
Started about a week ago for me, but seemed to be blocking some (not all) until yesterday.

**Comment by The18thPrimarch** [comment]
Yeah. The ublock and TTV Pro stopped working maybe 2 weeks ago and stopped using those entirely since the scripts were working. Now scripts are donezo too

**Comment by pixeltris** [comment]
Did you see #241?

- `vaft` was fixed by https://github.com/pixeltris/TwitchAdSolutions/commit/02447140c7522721601ac62c4fb47c7757e054d7 for #241
- `video-swap-new` is not impacted by the above issue and should be working without issue since #236
- `AdGuard Extra` Twitch specific code I think is maintained by @stanislav-atr. I'm not 100% sure where the code actually resides in terms of open source stuff but you can probably report issues here https://github.com/AdguardTeam/AdGuardExtra. Looking at the userscript it's impacted by the above issue and needs fixing
- `TTV Pro` there is an open issue https://github.com/younesaassila/ttv-lol-pro/issues/322

**Comment by The18thPrimarch** [comment]
THank you for this brother checking now. 

QUestion, do these scripts update automatically? Or are we needing to update them manually?

**Comment by The18thPrimarch** [comment]
> Did you see #241?
> 
> * `vaft` was fixed by [0244714](https://github.com/pixeltris/TwitchAdSolutions/commit/02447140c7522721601ac62c4fb47c7757e054d7) for [Seems like it just stopped working again #241](https://github.com/pixeltris/TwitchAdSolutions/issues/241)
> * `video-swap-new` is not impacted by the above issue and should be working without issue since [Script stopped working today #236](https://github.com/pixeltris/TwitchAdSolutions/issues/236)
> * `AdGuard Extra` Twitch specific code I think is maintained by @stanislav-atr. I'm not 100% sure where the code actually resides in terms of open source stuff but you can probably report issues here https://github.com/AdguardTeam/AdGuardExtra. Looking at the userscript it's impacted by the above issue and needs fixing
> * `TTV LOL PRO` there is an open issue [Support *.playlist.ttvnw.net weavers younesaassila/ttv-lol-pro#322](https://github.com/younesaassila/ttv-lol-pro/issues/322)

THank you for this brother checking now.

QUestion, do these scripts update automatically? Or are we needing to update them manually?
Question also for video-swap-new script. Just so I know if it's working properly or not, does it play the ad in the main screen and minimize the stream to the right side of your page? Or is it supposed to not display an ad at all?

Also, vaft still does not work. I got an ad upon entering the stream.

Using Chrome and Tampermonkey for my ScriptManager

**Comment by pixeltris** [comment]
> QUestion, do these scripts update automatically? Or are we needing to update them manually?

Depending on your userscript manager settings it should prompt you to update. Your userscript manager should also show you which version of the script you're on. The current version for `vaft` is:

https://github.com/pixeltris/TwitchAdSolutions/blob/8632ee23ad2537527f09f6c1d3192036ea12eca3/vaft/vaft.user.js#L4

> Just so I know if it's working properly or not, does it play the ad in the main screen and minimize the stream to the right side of your page? Or is it supposed to not display an ad at all?

There is a little label at the top left of the stream which says `Blocking ads` when ads are actively being blocked. At other times there's no indication that the script is active other than a console log.

> Also, vaft still does not work. I got an ad upon entering the stream.

It's possible something could have changed since #241 but I have no indications so far.

**Comment by The18thPrimarch** [comment]
Ah okay understood. Well, sadly they both still do not work for me. The best so far is just video swap which puts the stream on the right side of screen but nothing else. Is there anything I could provide to you in regards to these issues to help for a fix? First time commenting so im unsure what you need or if this is the proper way my apologies. 

![image](https://github.com/pixeltris/TwitchAdSolutions/assets/99460282/8a9b4cc1-7bd3-43d5-8e54-72c60b663b38)

**Comment by stevenya97** [comment]
As a side, I see you have both ADP and uBlock extensions whitelisted for twitch.tv, as indicated by the grey icons. Best would be to disable ABP and just let uBlock do its thing to avoid multiple adblockers conflicting with each other. Are you able to share your list of extensions? Maybe something else is conflicting with the userscript and stealing focus

**Comment by The18thPrimarch** [comment]
Yes absolutely. Images below.

Oh ok. Ill remove it then for good measure.

![image](https://github.com/pixeltris/TwitchAdSolutions/assets/99460282/a2698568-416c-4d5a-ad6b-b7ff7afc238a)
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/99460282/4aa2b966-a41b-412b-aaf1-59cb9a00d058)
