### ISSUE TITLE
ublock origin twitch video swap not working anymore.

### ISSUE THREAD

**Issue by mmizab** [pixeltris/TwitchAdSolutions#309]
you fuckedup the script I had to roll back to old version.

**Comment by andy1k** [comment]
Not working anymore

**Comment by zPhenomm** [comment]
Vaft doesn't work for me anymore, getting prerolls. It worked a few hours ago, there might be a problem with the new commit.

**Comment by pktpls** [comment]
Same for vaft/vaft-ublock-origin.js, going back to previous commit works

**Comment by pixeltris** [comment]
My bad, fixed in https://github.com/pixeltris/TwitchAdSolutions/commit/477085016b84beba8ccf0035689dd4b51fce929d

**Comment by pktpls** [comment]
Hehe nice one - works here, thank you!

**Comment by tmud67** [comment]
So how do I fix this now?

**Comment by webmastir** [comment]
@tmud67 restart your browser. It should pull the latest changes.

**Comment by tmud67** [comment]
Hmm I turned on and off the blocker, reset the computer, still not working

**Comment by webmastir** [comment]
@tmud67 What URL do you have configured for `userResourcesLocation`  in uBlock Origin > Advanced Settings?

**Comment by tmud67** [comment]
It is working now just took a minute i guess

**Comment by omnosti** [comment]
I had to remove the master link from my filter lists, it suddenly started messing up the formatting on non-Twitch websites for me.

**Comment by pixeltris** [comment]
@omnosti I'm not sure how that would be possible. This is the first line of code:

https://github.com/pixeltris/TwitchAdSolutions/blob/1c41aeab0d8922e96da62903896f2785c169e932/vaft/vaft-ublock-origin.js#L3

And the filter is `twitch.tv##+js(twitch-videoad)`

**Comment by SteezyGH** [comment]
Whenever I load any website with this list enabled in uBlock they are all in text mode, here's a screen cap of it on this very issue page, along with a capture of the uBlock Origin Asset Logger. The logger also throws up a bunch of invalid filter errors upon reloading when enabling the list. Not sure if you'd want this as a separate issue.

![Screenshot (1666)](https://github.com/user-attachments/assets/80f04fb3-6f1b-4842-baed-e6ad01b92d0b)

**Comment by pixeltris** [comment]
The url isn't a filterlist. Read the instructions in the readme on how to use url https://github.com/pixeltris/TwitchAdSolutions?tab=readme-ov-file#applying-a-script-ublock-origin

**Comment by AlexIs387** [comment]
> The url isn't a filterlist. Read the instructions in the readme on how to use url https://github.com/pixeltris/TwitchAdSolutions?tab=readme-ov-file#applying-a-script-ublock-origin

I did it and ads didn't stop, even after restarting the browser, why don't you admit that this will not work and stop fooling?

**Comment by SteezyGH** [comment]
> The url isn't a filterlist. Read the instructions in the readme on how to use url https://github.com/pixeltris/TwitchAdSolutions?tab=readme-ov-file#applying-a-script-ublock-origin

Whoops yeah that's what the problem was, everything works fine for me now sorry for the misunderstanding

**Comment by Xe11o** [comment]
> @tmud67 What URL do you have configured for `userResourcesLocation` in uBlock Origin > Advanced Settings?

It's not working for me currently. `userResourcesLocation` value is `https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/722f5b96241ef1d92998b87f941690e47e475379/video-swap-new/video-swap-new-ublock-origin.js`, have applied and restarted browser.
