### ISSUE TITLE
getting twitch video errors (Error #1000) very often

### ISSUE THREAD

**Issue by jackp7** [pixeltris/TwitchAdSolutions#355]
I get the issue with both vaft and video swap new running with userscript not ublock

**Comment by mryx007** [comment]
same here.

**Comment by ev88** [comment]
edit: I'm using the uBlock method, to clarify:

None of the streams are loading if I have  userResourcesLocation https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/master/video-swap-new/video-swap-new-ublock-origin.js

Removing that brings things back to normal.

**Comment by jackp7** [comment]
That would only apply to running the script with ublock

**Comment by livvydoodlez** [comment]
Issue is happening with me now too, Videos will not load unless adblock is completely turned off using the video swap method with tampermonkey

**Comment by zach004** [comment]
Same problem here.

**Comment by TheNotZen364** [comment]
Same issue here

**Comment by bugreporter2334** [comment]
No streams load while using video-swap-new, but some do and some don't with AdGuard Extra. I'm using both as userscripts.

**Comment by cupid777-cpu** [comment]
for me its the same issue but it shows (Error #2000) think its ov

**Comment by theorist-complex** [comment]
im another one...using the ublock method, no streams loadinng, getting error 2000

**Comment by Juokye** [comment]
User with tampermonkey here and error 2000 too... Damn.

**Comment by pixeltris** [comment]
Probably same as #363. Will reopen / look into if not related.

**Comment by eccccco** [comment]
also getting (Error #1000) often
on **Firefox**
with **vaft script**
via **Tampermonkey**

**Comment by kodiakhub** [comment]
Could you test this userscript: [AdGuard Extra v1.0.696](https://github.com/AdguardTeam/AdGuardExtra?tab=readme-ov-file#userscript)? It should also fix the #1000 error issue. See: [AdguardTeam/AdGuardExtra#599 (comment)](https://github.com/AdguardTeam/AdGuardExtra/issues/599#issuecomment-...)

**Comment by PZaphiro** [comment]
> Could you test this userscript: [AdGuard Extra v1.0.696](https://github.com/AdguardTeam/AdGuardExtra?tab=readme-ov-file#userscript)? It should also fix the #1000 error issue. See: [AdguardTeam/AdGuardExtra#599 (comment)](https://github.com/AdguardTeam/AdGuardExtra/issues/599#issuecomment-...)

This didn't work for me unfortunately on Chrome with uBlock also enabled. Tested with the other Tampermonkey userscripts both enabled and disabled alongside Adguard Extra Userscript.

**Comment by kodiakhub** [comment]
> This didn't work for me unfortunately on Chrome with uBlock also enabled. Tested with the other Tampermonkey userscripts both enabled and disabled alongside Adguard Extra Userscript.

@PZaphiro Could you please test again using only uBlock Origin (Default settings) + [AdGuard Extra Extension v1.0.696](https://chromewebstore.google.com/detail/adguard-extra/gkeojjjcdcopjkbelgbcpckplegclfeg) for testing purpose. If you're still seeing the error, which twitch stream link is showing it? 🤔

**Comment by PZaphiro** [comment]
I don't seem to get the Error #1000! For me, ads still roll after a few seconds with Adguard, vaft, and uBlock enabled, but if I change the user-agent in Chrome to Firefox Windows, it seems to kill any ads from loading. Might be a temporary workaround for the time being.

**Comment by xxsnookumsxx** [comment]
I've been getting the #1000 error message and having to reload tab to reconnect to the stream.

I did a bit of experimenting and I think I may of found the issue or something relating to it.

Until recently and until I started getting the error message the filters I had in my UBO that blocked all twitch ads without issue were as follows:

* edge.ads.twitch.tv * block
* https://assets.twitch.tv/assets/features.ads.components.dsa-wizard.components.dsa-button.component-be49fcca56d4fcd07863.js script block
* https://assets.twitch.tv/assets/features.video-player-core.components.video-ads.pushdown-sda-eligibility-9ab196592fd741992edb.js script block
* https://assets.twitch.tv/assets/features.ads.components.dsa-wizard.components.dsa-modal.dsa-modal-manager-a833ab3c0532488775a2.js script block
* https://assets.twitch.tv/assets/features.video-player-core.components.video-ads.audio-ad-overlay.component-76c620b9ae6228c82239.js script block
* https://assets.twitch.tv/assets/features.video-player-core.components.video-ads.audio-ad-overlay.component-3fe84e7dbf30e285c7cd.js script block
* https://assets.twitch.tv/assets/features.video-player-core.components.video-ads.stream-display-ad.pushdown.portal-1e0712f4caa814f95829.js script block

Now then, I decided to recheck  my filters by going on twitch channels I knew to have ads enabled and watched the UBO console to see what got blocked and what didn't, I then noticed the following getting through:

* https://assets.twitch.tv/assets/features.video-player-core.components.video-ads.audio-ad-overlay.component-d74158bfd9ea923ff5c4.css stylesheet block

Since I've added that last ad link to my filter list I've had no more error #1000 on any channels since.

Also, kind of on a side note, I've heard a few DJ's on twitch say they've had sound issues after an ad has played, their audio has gone mute while using OBS, so it could be coincidence or maybe that overlay ad is creating the issue for them.

Anyway, just thought I'd share my knowledge in the hopes it may help others out.

**Comment by pixeltris** [comment]
Reopening for @silverlays https://github.com/pixeltris/TwitchAdSolutions/issues/404#issuecomment-3059500058. I'm looking for additional information. I briefly had error 2000 or 1000 when testing a few weeks ago, I think some m3u8 request was returning an error code. I can't remember if ads were being shown at the time.

What information I'm looking for:
- What browser you're using
- Which script you're using
- Are there any m3u8 requests which fail. If so what is the error code?
- Are ads actively being blocked when the error occurs?
- Do you get error 1000 / 2000 when ads aren't being displayed / prior to the first ad being displayed?

**Comment by silverlays** [comment]
Hi @pixeltris 

* I'm using Chrome (Ublock desactived, only tampermonkey activated)
* I tried the 2 scripts (video-swap-new & vaft)
* I've got the Error 2000 when a midroll-ads trigger but ONLY on source quality (1080p60+)
* I think so. If I change resolution when the error occur to 720p60, everything works fine and no more error after that. And if i swap to 720p60 at launch, the error never occured.
* No the error only occur on midroll ads, never the first on launch.

One information to give you, I'm using the popout version of the URL, like this: https://player.twitch.tv/?enableExtensions=true&channel=$$1&parent=twitch.tv&player=popout&quality=chunked&muted=false

I didn't dig into the requests but I can try to gather the informations you need. Keep me in touch.

Thanks in advance

**Comment by theorist-complex** [comment]
> Anyway, just thought I'd share my knowledge in the hopes it may help others out.

Heya @xxsnookumsxx  Is there any chance I can get a screenshot of your twitch filter list in UBO showing those you listed in your post so i can compare my own? I believe maybe my formatting is incorrect and Im just not sure. Thanks either way for sharing!

**Comment by xxsnookumsxx** [comment]
> > Anyway, just thought I'd share my knowledge in the hopes it may help others out.
> 
> Heya [@xxsnookumsxx](https://github.com/xxsnookumsxx) Is there any chance I can get a screenshot of your twitch filter list in UBO showing those you listed in your post so i can compare my own? I believe maybe my formatting is incorrect and Im just not sure. Thanks either way for sharing!

I've since tweaked my list due to there being another css for the audio, so here is the updated version.
If you add the following  to your filters, it will auto block any urls with ads in their names, so it will block the edge.twitch ads as well as all the other ads links I'll list below

These three lines will block ads in scripts and css and edge ads in any/all urls. 
||*edge.ads.twitch.tv*$all
||*ads*$script
||*ads*$css

This allows the threads links to come through so they don't get caught up in the ads blocks above.
@@*threads*$script

This is what gets blocked:
https://assets.twitch.tv/assets/features.video-player-core.components.video-ads.audio-ad-overlay.component-d74158bfd9ea923ff5c4.css

https://assets.twitch.tv/assets/features.ads.components.dsa-wizard.components.dsa-modal.dsa-modal-manager-a833ab3c0532488775a2.js

https://assets.twitch.tv/assets/features.video-player-core.components.video-ads.stream-display-ad.pushdown.portal-1e0712f4caa814f95829.js

https://assets.twitch.tv/assets/features.video-player-core.components.video-ads.pushdown-sda-eligibility-9ab196592fd741992edb.js

https://assets.twitch.tv/assets/features.video-player-core.components.video-ads.stream-display-ad.pushdown.portal-1e0712f4caa814f95829.js

https://assets.twitch.tv/assets/features.video-player-core.components.video-ads.audio-ad-overlay.component-09ba12bf46d45933f7e3.js

edge.ads.twitch.tv

This is what gets enabled:
https://assets.twitch.tv/assets/features.whispers.components.whisper-threads-bar-8362637fdf9726213fcf.js

```
This is what I mainly use for all sites now though, then I'll tailor a white list for those sites which give major issues.
||*ads*$script
||*ads*$css
@@*threads*$script
||*admanager*$all
||*bannerlinks*$all
||*pagead*$all
||*sidead*$all
||*bottomad*$all
||*topad*$all
||*doubleclick*$all
||*trafficjunky*$all
||*safeframe*$all

```

19th July 2025
New update: I did some deep diving into Twitch.tv's code with the help of an AI.

```
||twitch.tv/cdn-cgi/trace
! ||gql.twitch.tv/gql^$xmlhttprequest,domain=twitch.tv,important (This breaks chat, can read chat but not mesage, remove ! to enable)
||static.twitchcdn.net/assets/*ads*
||player.twitch.tv/js/*ad*
||*edge.ads.twitch.tv*$all
```

**Comment by theorist-complex** [comment]
Hey thanks so much @xxsnookumsxx 

I really appreciate you taking the time out of your day to go over this for me.

**Comment by xxsnookumsxx** [comment]
@theorist-complex It's a pleasure to help out, if I come across anything else hidden behind the scenes as they say, I'll pop back in with updates, but for now it's working about 98% of the time, but if anyone else comes across anything and is unsure how to block it, feel free to post it and I'll see if I can figure out a work around, I love the challange lol.

Happy adfree watching

**Comment by garbb** [comment]
@xxsnookumsxx 
You can include * in the post by using putting them between \` characters or clicking the code button `<>`
like this
```
||*ads*$script
||*ads*$css
```

**Comment by xxsnookumsxx** [comment]
@garbb Thank you for your reply, that did the trick nicely, updated my post to use code.
Much appreciated.

**Comment by Agentevans179** [comment]
Im getting error 2000 as well
This is when loading a stream and the preroll wants to play. It spins for about 5-8 minutes then fails with an error 2000
On brave, ublock origin, https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/master/video-swap-new/video-swap-new-ublock-origin.js 
Please let me know if theres a working script I SHOULD be working as this ones worked for me for a while now. Only recently went south.

**Comment by TheAGames10** [comment]
I can no longer watch Twitch again, am now getting the same freezing/unplayable stream when trying to use any of the two scripts or when I try to use Brave shields by themselves. @pixeltris 

I am unsure how to fix this as I was watching streamers I enjoy a few minutes ago, but now am unable to because of this endless loading issue whenever Twitch ads show up. (Using Brave Shields with Tampermonkey, tried using each of the two scripts one by one, but both don't work anymore)

I cannot even click on a random stream like Vinesauce without having the pause and the endless freezing. (this is just like the issue that people came across a few months ago too.)

**Comment by ghost** [comment]
Unfortunately, i still get error #1000, especially when I join a stream, after about 5 minutes (vaft for uBlock Origin, Firefox/Edge)

**Comment by Koodikalle** [comment]
> Unfortunately, i still get error #1000, especially when I join a stream, after about 5 minutes (vaft for uBlock Origin, Firefox/Edge)

same here, i changed to brave browser and working perfectly fine

**Comment by rustyvanilla** [comment]
This issue only happens when watching streams in 1080p or higher, a script that switches to 720p during the ad then switches back to the original quality would be great.

**Comment by Squtzy** [comment]
Been getting error 2000 a lot lately. Doesn't seem to be channel specific. Nothing has changed on my end during the time where I have gotten it more frequently

Using Brave Browser, Video-Swap-New via ViolentMonkey

**Comment by sangohan** [comment]
I dont know if this helps, but one of the error messages in the console is 

```
18:14:34.968 Player stopping playback - error 0�:9 (ErrorNetworkIO code -1 - WorkerGlobalScope.fetch: :// is not a valid URL.) amazon-ivs-wasmworker.min-96ae2717290f1bdba0b6.js:1:49765

```

**Comment by pixeltris** [comment]
@sangohan thanks for the error. I think that is saying the m3u8 has an entry which just says `://`. I'm not sure why. Which script are you using? Could you try the latest version https://github.com/pixeltris/TwitchAdSolutions/commit/9cae451c04a9a94859da7de19c367b58afdd95bc it may potentially fix that, not 100% sure.

EDIT: I saw that exact error today `WorkerGlobalScope.fetch: :// is not a valid URL` under `video-swap-new`. The script never saw ads and therefore didn't modify anything so as far as I can tell that is fully Twitch's fault.
