### ISSUE TITLE
Ads showing again

### ISSUE THREAD

**Issue by deecee40** [pixeltris/TwitchAdSolutions#471]
Chrome - Version 142.0.7444.163 (Official Build) (64-bit)
Vaft and Tampermonkey
Ads showing again. Likely update yesterday on Twitch.

I was on old script, updated to newest, issue persists.

Yeah, its not working on Firefox either. Either its midrolls or something, but its showing ads. Was using just Adblockers without the script as well, it worked fine for a while too but now thats broken. Think its a mix of adblockers (UBO/UBOL) and script that need updating

EDIT Nov 17/25 - Still occurring, it blocks ads, it just does not block midrolls, it will say its blocking, then eventually show them, a refresh fixes the timer to just 30 seconds, it freezes after 5 seconds then loads eventually. Twitch may have won, maybe Turbo is the way to go with how much I use Twitch. Tried AdblockExtra, no luck.

**Comment by mrbuurns** [comment]
same here starting today
Brave 1.84.139
newest Vaft via Violentmonkey

**Comment by Azaius0** [comment]
Just got one midroll that wasn't blocked but the next one was. Using the video-swap-new script on Opera GX 123 with tampermonkey.

**Comment by Firey34** [comment]
Starting to experience mid roll ads too..currently using the most updated version of firefox

**Comment by pixeltris** [comment]
Is it midrolls only? Does it make any difference logged in vs logged out? Currently I'm only testing logged out. When you get ads if you open the page in a new tab does that new tab also get ads? If you open a real embed player (e.g. https://twitchls.com/ninja) *((without the script active))* while you're getting ads on the regular site, does that also get ads (real ads, not commercial screen)?

**Comment by 543r05** [comment]
Microsoft Edge 142.0.3595.53
Tampermonkey 5.4.0
video-swap-new 1.47

Midrolls while using an account and without an account. Tested while logged in vs InPrivate window and got actual advertisements on both.

**Comment by affdeus** [comment]
the player "refresh" and reduce the quality with the "blocking midrolls ads" in the top left, then it "refresh" again and back to the high quality (auto) but still have the "blocking midrolls ads" msg and after few seconds the actually ads plays...
_*on Chrome with vaft script_

<img width="1346" height="818" alt="Image" src="https://github.com/user-attachments/assets/ee0bcef0-2ffa-400e-ab2a-3bf8e1fc1f9d" />

**Comment by Fanatiikon** [comment]
Can confirm i've also started getting ads today. Same as affdeus. The player changes quality and says blocking ads then after  a second the ad starts playing but it continue saying blocking ads. If you refresh the page you skip the ad with the adblock kicking in.

**Comment by Myoko** [comment]
I'm seeing ads again today too!

**Comment by TheDeeGee** [comment]
Confirmed.

Using Video-Swap-New via uBlock Origin on Edge.

**Comment by Meppyman** [comment]
Yep they have pulled ahead... just happened to me for first time in a long time tonight. mid roll when I switched to mod view but also showing in normal view now FF 145.0 on Windows.

**Comment by nacedos** [comment]
I was using the uBlock script and FF 145.0. Started seeing ads again in the approximate time frame as 1~2 days as well, just to realise that the `userResourcesLocation` was `unset` in the advanced settings (I didn't change it).
Not sure what caused this, but I decided to swap to `TTV LOL PRO` proxy from this repository and so far I haven't seen any ads.

**Comment by naunaud84820** [comment]
hi same for me with opera gx

**Comment by pixeltris** [comment]
Thumbs up OP if you're seeing ads. In the sake of working torwards a fix any further comments stating you're seeing ads or that you're having issues with anything else will be marked as off-topic.

If you want a solution right now try `TTV LOL PRO` ([chrome](https://chrome.google.com/webstore/detail/ttv-lol-pro/bpaoeijjlplfjbagceilcgbkcdjbomjd) / [firefox](https://addons.mozilla.org/addon/ttv-lol-pro/) / [code](https://github.com/younesaassila/ttv-lol-pro)). If you don't want to use a proxy solution try `Alternate Player for Twitch.tv` ([chrome](https://chrome.google.com/webstore/detail/alternate-player-for-twit/bhplkbgoehhhddaoolmakpocnenplmhf) / [firefox](https://addons.mozilla.org/en-US/firefox/addon/twitch_5/)) or try this userscript https://greasyfork.org/en/scripts/371186-twitch-mute-ads-and-optionally-hide-them/code.

I'm looking for someone who is regularly getting ad leakage to try an embeded player without any Twitch ad blocking solutions enabled (e.g. https://twitchls.com/ninja). Do you ever see real ads (not the commercial screen) on the embeded player with **all Twitch ad blocking scripts disabled**?

Thanks.

**Comment by novalaunchersa** [comment]
> Thumbs up OP if you're seeing ads. In the sake of working torwards a fix any further comments stating you're seeing ads or that you're having issues with anything else will be marked as off-topic.
> 
> If you want a solution right now try `TTV LOL PRO` ([chrome](https://chrome.google.com/webstore/detail/ttv-lol-pro/bpaoeijjlplfjbagceilcgbkcdjbomjd) / [firefox](https://addons.mozilla.org/addon/ttv-lol-pro/) / [code](https://github.com/younesaassila/ttv-lol-pro)). If you don't want to use a proxy solution try `Alternate Player for Twitch.tv` ([chrome](https://chrome.google.com/webstore/detail/alternate-player-for-twit/bhplkbgoehhhddaoolmakpocnenplmhf) / [firefox](https://addons.mozilla.org/en-US/firefox/addon/twitch_5/)) or try this userscript https://greasyfork.org/en/scripts/371186-twitch-mute-ads-and-optionally-hide-them/code.
> 
> I'm looking for someone who is regularly getting ad leakage to try an embeded player without any Twitch ad blocking solutions enabled (e.g. https://twitchls.com/ninja). Do you ever see real ads (not the commercial screen) on the embeded player with **all Twitch ad blocking scripts disabled**?
> 
> Thanks.

I tried many extensions yesterday and any of them is working. With TwitchAdSolutions I see real ads, with TTV I see commercial screen, with alternate player the stream just freezes and goes off when commercial break comes, with Purple AdBlock the stream crashes and show error 2000 when commercial break comes. It's curious that each one shows a different response.

**Comment by dvanco** [comment]
FWIW - FF on MacOS - vaft showing ads again but video-swap-new working fine.

**Comment by RasmusAntons** [comment]
I've been getting some ads yesterday and today with video-swap-new. Now I watched https://twitchls.com/ssanolive for about an hour and a half without video-swap-new but ublock origin still on and I only got the "Commercial break in progress" screen (three times). Switched back to twitch.tv and started seeing ads again.

**Comment by Ross-Clark** [comment]
using https://twitchls.com with no ad block solution i get the "commercial break in progress" screen but no proper ads in ~1 hr viewing
windows, chrome, logged in, no extensions

**Comment by RayFungDev** [comment]
Not sure how many people this is gonna reach, but I'm a solo dev and has been developing my own Twitch ad block extension, it's called `Twitch HLS Player (No Ads)`, it took me almost a year to make so I'm treating it very seriously. (I didn't even know JS at all before that)

I've been very quiet about it but today I finally shadow dropped the version 1.9.9, which has built-in re-implemented VAFT/video-swap ad block solution inspired by pixeltris (same concept adapted), **I've designed it such a way that you can still watch the ads while it's blocked (eg. to support the streamer), it's the default setting & highly recommended to do so 🙂.** (you can set the Twitch player to 160p to save bandwidth)

_Chrome Web Store Link :_ https://chromewebstore.google.com/detail/twitch-hls-player-no-ads/dmopcigmgeaagapbcfolkiemcoplgdei (please don't mind the 1 star reviews, my last update was too long ago...)

Until version 2.0.0 official release, I really am just looking for people to use & test it out, cuz so far it has just been me using it locally for my own purposes. Hope Twitch devs don't look around in here...

**Comment by LetsPlayNintendoITA2023** [comment]
> Not sure how many people this is gonna reach, but I'm a solo dev and has been developing my own Twitch ad block extension, it's called `Twitch HLS Player (No Ads)`, it took me almost a year to make so I'm treating it very seriously. (I didn't even know JS at all before that)
> 
seems to be working i'll do some testing thanks

**Comment by nogenem** [comment]
I'm also getting midroll ads from time to time on twitch ;/

Brave 1.84.139 (Versão oficial) 64 bits
Chromium: 142.0.7444.163
video-swap-new v1.47 with tampermonkey

**Comment by pixeltris** [comment]
My assumption right now is that about a week ago Twitch started selectively validating requests using the low resolution player types (see #461) which resulted in the "commercial break in progress" screen (due to falling back to the `embed` player type). Then on Friday of this week they did the same for the `embed` player type which resulted in ad leakage.

It's probably possible to fix both if their validation checks are met. I'm personally not running into it in my tests so someone else in the community is probably going to need to help out.

I've made a very experimental attempt at fixing the `embed` player type which probably wont work but you can leave feedback on it here https://github.com/pixeltris/TwitchAdSolutions/pull/472

As mentioned I'm keeping this issue 100% focused on people contributing towards fixing the player types that `vaft` / `video-swap-new` use to avoid ads. All other comments will be marked as off-topic but feel free to create a new issue to talk about anything else. Thanks.

**Comment by RayFungDev** [comment]
> It's probably possible to fix both if their validation checks are met. I'm personally not running into it in my tests so someone else in the community is probably going to need to help out.
> 

Hi @pixeltris, I've actually ran a test with the latest VAFT on the latest Firefox 4 days ago (13th Nov) running Summit1g stream (he's like midroll ads every 15 mins or so) and every ads are blocked without fail. Surprisingly, when I tried that same M3U8 URL & also a newly fetched one from `embed` player type (same platform) in my extension that's on Chrome, Twitch ads immediately went through (I was logged in as well) on both of them, so I kept my original implementation instead.

If I were to guess, maybe it's browser based but I can't be sure yet.

I also know that they recently made a change that logged out users always get ads (including direct playback token fetch), the small no ads 360p player would show for a few seconds (presumably the length of 1 fragment time due to mismatch) and then it'll get removed after showing a split second of the "Commercial Break in Progress" screen, that's one of the challenge I'm currently facing with my extension as well, so I'm focusing on another approach instead.

Anyway, I hope this helps! 😊

> As mentioned I'm keeping this issue 100% focused on people contributing towards fixing the player types that `vaft` / `video-swap-new` use to avoid ads. All other comments will be marked as off-topic but feel free to create a new issue to talk about anything else. Thanks.

Sorry about my off-topic reply earlier, I got too excited for people to test whether my extension's working after developing it for so long, I should definitely have start a new post but I'm quite paranoid about Twitch devs looking through here... 😅 (I mean to me it seems like Twitch can easily fix the solution if they wanted to? idk)

**Comment by Boskosauce** [comment]
I apologize if this is a useless comment but I seem to only be getting ads while watching 1440p streams using vaft.

Also a weird issue, there are times where the ad will start playing for a moment and then switch to the actual stream, and then I'll see the "Blocking midroll ads" and "Taking an ad break; stick around to support the stream!" at the top left corner. "Ad" at the top right corner and then "Learn More" at the bottom left corner.

**Comment by maronh** [comment]
browser vivaldi 
only adguard extra on. 
they did updated today though

works for me the ads gets sent to the right side muted.

**Comment by pixeltris** [comment]
@Boskosauce streams with 2k/4k (1440p+) quality settings currently briefly depend on the low resolution stream working at a 100% rate so that is the weirdness you experienced due to the failing low resolution stream.

@maronh AdGuard Extra has an additional low resolution player type which generally wasn't failing as much. `vaft` doesn't currently use it to reduce the amount of request spam (which is already pretty high).

Should hopefully be fixed by https://github.com/pixeltris/TwitchAdSolutions/commit/8d37319d094e3db2923c52f5f43356580505b0c4

I'm sure Twitch will make more changes like this going forward. If you want stability / not have to deal with this kind of thing I'd recommend sticking to a proxy solution such as TTV LOL PRO.

NOTE: If you're using uBlock Origin with a uBlock script from the repo, you need to get the latest permalink, apply it to uBlock Origin, then disable/enable uBlock Origin.

**Comment by deecee40** [comment]
Hopefully I won't get off-topic'd, but am testing now, just trying to find someone who does midrolls lol

EDIT - Midrolls test 1, quality dropped to 720p then 360p, then continued on no ads, quick refresh and back to normal. Good test 1. Will do more.

EDIT 2 - Midroll test 2, same process as test 1, so far so good. Will do more.

EDIT 3 - Midroll test 3, same process as test 1, looking good. There is 1 streamer who has invasive ones I want to test when he is on next

EDIT 4 - blocks invasive streamer with constant ads, WE ARE BACK DOODS <3 pixeltris

**Comment by Fusha** [comment]
Can confirm, the new video-swap-new version blocks ads once again. Thank you ☕

**Comment by iSWB** [comment]
> Can confirm, the new video-swap-new version blocks ads once again. Thank you ☕

Are you using the regular Twitch player? I'm still getting the frozen video when ads play on Alternate Twitch Player on Firefox with both vaft and video-swap.

**Comment by RayFungDev** [comment]
Just tested the new VAFT on the latest Firefox using uBlock origin, seems to be working 👍:

<img width="1920" height="1035" alt="Image" src="https://github.com/user-attachments/assets/3a8f6fc5-379c-483a-bb6e-800080388467" />

**Comment by salvadorzombie** [comment]
Win 7, Firefox (r3dfox)

On both vaft and video-swap-new, I no longer get a "Blocking ads/Blocking midroll ads" message, but at certain intervals (I don't even think they're ad intervals) the video just freezes and I sometimes get a 2000 error. This happens several times over the course of a minute or two, and happens whether I'm subscribed to a channel or not. It also seems to happen on certain channels, so possible A/B testing?

**Comment by salvadorzombie** [comment]
> Win 7, Firefox (r3dfox)
> 
> On both vaft and video-swap-new, I no longer get a "Blocking ads/Blocking midroll ads" message, but at certain intervals (I don't even think they're ad intervals) the video just freezes and I sometimes get a 2000 error. This happens several times over the course of a minute or two, and happens whether I'm subscribed to a channel or not. It also seems to happen on certain channels, so possible A/B testing?

One other thing I've noticed tonight, it seems to be happening less often on the channels where it happens. Not sure how relevant that is, but I want to give all the information I can.

**Comment by pixeltris** [comment]
@iSWB the developer of `Alternate Player for Twitch.tv` doesn't read the issues on this repo. You need to contact them directly. Twitch ad blocking solutions don't work in combination with each other as that's not how they are designed to work.

@salvadorzombie there's an open issue about error 2000 #355. My understanding is error 2000 is caused be m3u8 requests which fail. There should be a red error console log and a network error when it happens. If you can provide that information in the linked issue that would be useful.
