### ISSUE TITLE
Later versions of Vaft have massive issues with endless buffering

### ISSUE THREAD

**Issue by Jules-A** [pixeltris/TwitchAdSolutions#492]
Previously I was using Adguard Extra with uBlock Origin on Firefox and was only getting endless buffering rather rarely (100% on raids though) but had to look for new solutions since it was causing Youtube to detect an adblocker even when disabling the script on Youtube (not sure how the hell that happens).

This lead me to trying different solutions but with the proxy ones I still got ads and some others interfered with the BetterTTV extension and caused it to break.
Vaft doesn't seem to interfere but would cause endless buffering almost instantly and even after spending 2hrs trying all the different options which didn't help (neither did using as uBO resource).
Then I tried reverting to version 30 (since the buffering logic was majorly reworked) and so far it seems to be working fine for hours with the exception of raids that break it 100% of the time.

I was going to try have the tab reload after raiding to try fixing that issue but I wasn't sure how to detect it (are you able to add that as an option)?

**Comment by pixeltris** [comment]
[Comparing 30/33](https://github.com/pixeltris/TwitchAdSolutions/compare/v17...v20) there's a change which might potentially be causing the infinite buffering:

https://github.com/pixeltris/TwitchAdSolutions/blob/5a853805c6814b400ced0a64631a5b8c0cffc491/vaft/vaft.user.js#L712

Try changing that 5 to 0. Can't see anything else.

I don't watch Twitch enough to realistically help with the raid issue but AI gives a pretty reasonable answer. Question: write me a userscript which reloads the tab when the active channel changes due to a raid by intercepting history.pushState. (referrer=raid in url)

Answer:

```js
// ==UserScript==
// @name         Twitch Raid Tab Reloader
// @namespace    tampermonkey.net
// @version      2025.12.24
// @description  Full tab reload when a raid occurs (?referrer=raid)
// @author       You
// @match        www.twitch.tv*
// @grant        none
// @run-at       document-start
// ==/UserScript==

(function() {
    'use strict';

    /**
     * Wrap the original pushState to detect internal navigation.
     */
    const originalPushState = history.pushState;

    history.pushState = function(state, title, url) {
        // Execute the original pushState navigation
        const result = originalPushState.apply(this, arguments);

        try {
            // Create a URL object to parse parameters from the target URL
            const targetUrl = new URL(url, window.location.origin);

            // Check if the raid parameter is present
            if (targetUrl.searchParams.get('referrer') === 'raid') {
                console.log('[Raid Reloader] Raid detected. Reloading tab...');
                
                // Force a full page reload
                window.location.reload();
            }
        } catch (e) {
            // Fallback for relative or malformed URLs
        }

        return result;
    };
})();
```

**Comment by Jules-A** [comment]
>  if (position > 5 &&// changed from >0 to >5 due to issues with prerolls. TODO: Improve this, player could get stuck 
> Try changing that 5 to 0. Can't see anything else.

Didn't help.
Also I noticed that some raids worked fine with the revert so it's not 100% chance of failure like newer Adguard Extra or Vaft scripts are.

In regards to the reload, I might try that out but I'd probably want to also check if it's in a buffering state before reloading in case it worked fine. If that's possible obviously.

**Comment by pixeltris** [comment]
> Didn't help.

Well I cant see anything different between 30/33 that would make any difference to buffering. The diff is linked above.

> In regards to the reload, I might try that out but I'd probably want to also check if it's in a buffering state before reloading in case it worked fine. If that's possible obviously.

The script has buffering mitigation. It checks if the player is buffering and triggers pause/play when it detects it. If this code functions correctly it fixes the buffering and there's no reason to reload the tab. It would make more sense for you to play around with that code instead:

https://github.com/pixeltris/TwitchAdSolutions/blob/5a853805c6814b400ced0a64631a5b8c0cffc491/vaft/vaft.user.js#L699-L756

**Comment by Jules-A** [comment]
> > Didn't help.
> 
> Well I cant see anything different between 30/33 that would make any difference to buffering. The diff is linked above.

Okay... so... instead of setting to 0, removing that initial position check ends up fixing it.
While I didn't see any infinite buffering, there was some very brief black screens or buffering that lasts up to 5secs on pre-rolls and mid-roll buffing that's around a sec or so and might be possibly improved by changing the config.

About raids, with the old version of the script, I actually haven't noticed any issues with infinite buffering lately. I think the channels it initially occurred on were tabs that weren't reloaded and were running the newer version of the script still.

**Comment by pixeltris** [comment]
> Okay... so... instead of setting to 0, removing that initial position check ends up fixing it.

The initial position check is to avoid it pausing/playing before it starts playing the stream as if it does this it can take longer for there to be any playback and it looks weird to the user as it looks like the player is pausing. That's also why it was increased from 0 to 5.

> While I didn't see any infinite buffering, there was some very brief black screens or buffering that lasts up to 5secs on pre-rolls and mid-roll buffing that's around a sec or so and might be possibly improved by changing the config.

Yes there could be some improvements for sure. The 5 secs on preroll could be related to it doing pause/play early as mentioned (there's a console log when it does this). Or it could be related to there being too many network requests when the stream starts. It tries using minimal network requests for a period of time (briefly using just low resolution) but this time might need to be increased:

https://github.com/pixeltris/TwitchAdSolutions/blob/5a853805c6814b400ced0a64631a5b8c0cffc491/vaft/vaft.user.js#L37

Unfortunately I'm personally back to not watching Twitch at all so I'm unlikely to make any further changes. PRs are welcome for anyone who wants to improve the code or make config tweaks that work better.

**Comment by Jules-A** [comment]
Hmm... I noticed an issue with the older version, when stripping is required which seems very rare, I just get a black screen for the whole duration of the ad.

I tried playing around ways to improve the issues I was seeing and did manage to find some success (by checking for buffering more frequently if the count is > 0), however there appears to be another bug with resolution during ads, it seems to be stuck playing the stream at low res.

**Comment by pixeltris** [comment]
> when stripping is required which seems very rare, I just get a black screen for the whole duration of the ad

Yes when it needs to use stripping it can last for the full duration of the ad. You're at the mercy of the servers providing you with a clean stream.

> however there appears to be another bug with resolution during ads, it seems to be stuck playing the stream at low res

If you're talking about the latest version of the script if you increased `PlayerReloadMinimalRequestsTime` it will use low res only for that entire duration as that's what that setting does (uses 1 specific backup stream, which is currently set to low res). Otherwise it should be able to get higher resolution after `PlayerReloadMinimalRequestsTime`, would always recommend setting specific quality in the player settings rather than auto quality as it can prefer low res.

**Comment by Jules-A** [comment]
> If you're talking about the latest version of the script if you increased `PlayerReloadMinimalRequestsTime` it will use low res only for that entire duration as that's what that setting does (uses 1 specific backup stream, which is currently set to low res). Otherwise it should be able to get higher resolution after `PlayerReloadMinimalRequestsTime`, would always recommend setting specific quality in the player settings rather than auto quality as it can prefer low res.

Yeah, I was talking about the latest version and it was occurring default options with the position > 5 check removed. 
I only had success changing PlayerBufferingDelay, I saw too many other issues changing other values. Well, technically as a diff option: 
```
const bufferDelay = playerBufferState.numSame == 0 ? PlayerBufferingDelay : PlayerBufferingFoundDelay;
setTimeout(monitorPlayerBuffering, bufferDelay);
```

**Comment by djg007** [comment]
Still getting buffering on latest Firefox. Before there were times where during some mid-roll ads, a certain portion of the stream would loop and would need a refresh.

**Comment by pixeltris** [comment]
@djg007 repeating segments is definitely one of the bigger issues as it's difficult to detect https://github.com/pixeltris/TwitchAdSolutions/blob/master/issues.md#freezing--buffering--repeating-segments--audio-desyncs

As mentioned I'm not currently watching Twitch so it's extremely unlikely I'll be fixing this myself. PRs are welcome if  you'd like to put in the work to fix this.

One thing that might work is reloading the player or triggering pause/play as it switches the active m3u8. Might need to be done at a delay like 1-2 second after it occurs.

https://github.com/pixeltris/TwitchAdSolutions/blob/5a853805c6814b400ced0a64631a5b8c0cffc491/vaft/vaft.user.js#L584-L587

After the console log do one of the following:

- `postMessage({key: 'ReloadPlayer'});`
- `postMessage({key: 'PauseResumePlayer'});`
- `setTimeout(() => postMessage({key: 'ReloadPlayer'}), 1000);`
- `setTimeout(() => postMessage({key: 'PauseResumePlayer'}), 1000);`

Timing might need to be adjusted. Try it out.

Ref #199

**Comment by Jules-A** [comment]
> After the console log do one of the following:
> 
>     * `postMessage({key: 'ReloadPlayer'});`
> 
>     * `postMessage({key: 'PauseResumePlayer'});`
> 
>     * `setTimeout(() => postMessage({key: 'ReloadPlayer'}), 1000);`
> 
>     * `setTimeout(() => postMessage({key: 'PauseResumePlayer'}), 1000);`

All but `postMessage({key: 'PauseResumePlayer'});` just made things worse. There was still about 12 buffers during the midroll but I was able to at least get through them without permanent buffer. It failed on the midroll after that though.
Reload was causing it to keep switching between black screen and the screen which is super  broken then got perm buffer anyway.
Maybe if I were set it to reload after a minute it might fix the perm buffer.

EDIT: So far setting it to 60s seems to stop the infinite buffering but I think there should be a better way to detect if the ad was a midroll when it finishes and wait a second after it ends to pauseresume instead of doing it instantly.

**Comment by pixeltris** [comment]
> I think there should be a better way to detect if the ad was a midroll when it finishes and wait a second after it ends to pauseresume instead of doing it instantly.

You could add a delay to it just like the above code. The code for when the ad ends is here:

https://github.com/pixeltris/TwitchAdSolutions/blob/5a853805c6814b400ced0a64631a5b8c0cffc491/vaft/vaft.user.js#L594-L611

It's currently configured to reload the player when this happens rather than pause/play. But you can change that setting here:

https://github.com/pixeltris/TwitchAdSolutions/blob/5a853805c6814b400ced0a64631a5b8c0cffc491/vaft/vaft.user.js#L36

**Comment by Jules-A** [comment]
>You could add a delay to it just like the above code. The code for when the ad ends is here:

I tried that, even tried to only delay it for midrolls but it didn't work.

>ReloadPlayerAfterAd

I want to avoid that if possible as it's incredibly frustrating if you are listing to audio from the stream since it can occur very frequently...
Also, the fixbuffer option is 100% broken, even removing that <5 it doesn't log the attempts to fix so it's not even running the part that's supposed to fix it.
EDIT: ReloadPlayerAfterAd doesn't even fix the infinit buffering anyway.

**Comment by Jules-A** [comment]
Probably should add that the latest updates didn't fix a thing for me, pretty much just an instant endless buffer on the first ad.

**Comment by FrostbyteXXL** [comment]
I’d like to add that I’m also seeing playback issues in v35, while v33 runs quite stable for me.

I’m not getting endless buffering like described above, but I am seeing:

- noticeably more buffering compared to v33
- audio/video desync after ~2 ad breaks
- script-triggered pause/play or reload seems not to fix it
- manual pause → play in the Twitch player immediately resyncs
- occasional brief audio crackling

Tested Vaft with Low Latency both enabled and disabled.

Firefox 148.0
uBlock Origin 1.69.0
Tampermonkey 5.4.1

In v33 I changed these script parameters from default:

PlayerBufferingSameStateCount = 4
PlayerBufferingDoPlayerReload = false
ReloadPlayerAfterAd = false

I applied the same settings in v35, but the desync still occurs.

Since these issues do not occur in v33, this looks like a regression in the newer player/buffer handling.

**Comment by pixeltris** [comment]
@FrostbyteXXL there weren't any changes to how the buffering mitigation works. It was a Twitch internals API compatibility update for the buffering mitigation to function at all (it was broken in v33 when doing full reload of Twitch with page caching disabled). See https://github.com/pixeltris/TwitchAdSolutions/commit/3a1ff51d9cb2448cabdb25aba2e612ab8b02d8d3

**Comment by Jules-A** [comment]
Hmm... I got frustrated so I asked AI to try fix it, it seems to be working alright now for the past 2hrs, even raids working:

https://github.com/Jules-A/TwitchAdSolutions/commit/66c9772390282a443c9ca7c1980a2246c7418bec

Only issue seems to be that it reloads the player as soon as midroll ads start sometimes and console gives me [ERROR] [apollo] Received non-200 response from GraphQL. Error: Received non-200 response from GraphQL.

**Comment by pixeltris** [comment]
I don't see any logical changes there to the buffering mitigation other than the setting values and a removal of a double call to `doTwitchPlayerTask`. The double call could have been the cause of the issues. Hard to tell. Definitely something that should be fixed though that's for sure a bug.

**Comment by Jules-A** [comment]
> I don't see any logical changes there to the buffering mitigation other than the setting values and a removal of a double call to `doTwitchPlayerTask`. The double call could have been the cause of the issues. Hard to tell. Definitely something that should be fixed though that's for sure a bug.

Removing the double call alone didn't fix it. Neither did increasing the config values but after the bufferfix function was actually working again it was pausing twice sometimes after ad so I increased the min to 12secs (but that was just to be safe).

**Comment by pixeltris** [comment]
The only other change would be the null check of `position` and the removal of `position > 5`. Everything else is identical to before other than reformatting of code.

Happy to apply some of these changes but not sure about the removal of `position > 5` as it will consistently cause an immediate pause/play when entering streams with prerolls which looks weird and results in streams taking longer to load.

**Comment by Jules-A** [comment]
I'll check if it still works with the position check with the null checks now in place.

EDIT: Nah, it's still broken with it, I assume position never gets updated so it's never >5 (or 3 which I also tested) so it doesn't run the buffer fix.

**Comment by pixeltris** [comment]
I implemented the core of the changes here https://github.com/pixeltris/TwitchAdSolutions/commit/cebf3d73f0743f99708812dfeb946be701f1a97f and I made the position check optional (disabled by default). So that should be the same as you were running. See how it goes. If there's still issues try doing some tweaks again, happy to take a look at any.

**Comment by Jules-A** [comment]
> I implemented the core of the changes here [cebf3d7](https://github.com/pixeltris/TwitchAdSolutions/commit/cebf3d73f0743f99708812dfeb946be701f1a97f) and I made the position check optional (disabled by default). So that should be the same as you were running. See how it goes. If there's still issues try doing some tweaks again, happy to take a look at any.

1hr10min so far with 8 streams open and no issues with perm buffer so far. During ads it seems to pause more often than the script I was running (and maybe take slightly longer, maybe cache?) but I forgot to mention I did actually reduce scope.PlayerBufferingMinRepeatDelay to 10000 and had more success with that (since I noticed an edge cases where it was actually needed to be faster than 12s). It could probably be quite a bit lower even, I was just doing safer values first to get it working first. The same with the other config options maybe, they were just the standard AI response of adjust values before changing code and I didn't change them.

EDIT: Testing not reloading after ad and it seems to work now and slightly better experience so far (only 40mins).

**Comment by Jules-A** [comment]
Still no issues with permanent buffering, I think it's safe to close now.

**Comment by pixeltris** [comment]
Another problem with `PlayerBufferingPrerollCheckEnabled = false` is that if you open new tabs with middle click and then wait a while before you actually go to the tab the stream ends up being in a paused state and requires the user to manually unpause the stream. This is pretty bad behavior because this is a pretty common usage pattern where users open multiple streams

**Comment by pixeltris** [comment]
In https://github.com/pixeltris/TwitchAdSolutions/commit/f8f86706daf90daa534b26bce5b2f01238667d5f I added some additional checks to prevent the player starting in a paused state when opening streams in a new tab. I lowered `PlayerBufferingMinRepeatDelay` down to 8000 as I feel 12000 was too high.

**Comment by Jules-A** [comment]
> In [f8f8670](https://github.com/pixeltris/TwitchAdSolutions/commit/f8f86706daf90daa534b26bce5b2f01238667d5f) I added some additional checks to prevent the player starting in a paused state when opening streams in a new tab. I lowered `PlayerBufferingMinRepeatDelay` down to 8000 as I feel 12000 was too high.

I had some problems still with 8000, just trying the latest release I saw the bufferfix apply 5 times during an ad which is extremely annoying.
I'm currently using https://github.com/pixeltris/TwitchAdSolutions/compare/master...Jules-A:TwitchAdSolutions:bufferfix3
and now that the bufferfix is actually working now, I haven't had any issues with not reloading the player so it's like 25x less time spent in buffering state. Also I think checking more frequently helps as well. I only see the bufferfix apply 2x per ad.
